import type { StickyNote } from "./types";

const now = Date.now();

// Colors are now derived from kind in the component;
// `color` here is preserved for backwards compatibility but ignored visually.
export const seedNotes: StickyNote[] = [
  {
    id: "n-1",
    kind: "need",
    author: "Dee",
    role: "Newcomer · Operations",
    body: "Looking for a half-day virtual newcomer onboarding so the next cohort walks in primed. Anyone want to co-design it with me?",
    tags: ["onboarding", "newcomer"],
    color: "",
    rotation: -2.4,
    createdAt: now - 1000 * 60 * 60 * 18,
    replies: [
      {
        id: "r-1",
        author: "Camille Newsom",
        body: "I'd love to help — I ran a similar Beg-Brag-What-If prep at our org. Find me at breakfast.",
        createdAt: now - 1000 * 60 * 60 * 12,
      },
    ],
  },
  {
    id: "n-2",
    kind: "offer",
    author: "Kyle Shannon",
    role: "Speaker · AI Salon",
    body: "Will run a 30-minute hands-on AI parlor-trick session — get people to their first 'aha' moment with the tools.",
    tags: ["AI", "workshop"],
    color: "",
    rotation: 1.8,
    createdAt: now - 1000 * 60 * 60 * 22,
    replies: [],
  },
  {
    id: "n-3",
    kind: "need",
    author: "Mark Stephens",
    role: "Board Member",
    body: "Need volunteers to help shape the Raleigh 2027 agenda — especially anyone with NC State, Duke, or UNC ties.",
    tags: ["Raleigh", "students"],
    color: "",
    rotation: -1.1,
    createdAt: now - 1000 * 60 * 60 * 30,
    replies: [],
  },
  {
    id: "n-4",
    kind: "offer",
    author: "Jenny Heaton",
    role: "Prior Board Chair",
    body: "Happy to mentor 2 newcomers this cycle. 30-minute pre-event call, then ongoing through the year.",
    tags: ["mentorship"],
    color: "",
    rotation: 2.6,
    createdAt: now - 1000 * 60 * 60 * 40,
    replies: [
      {
        id: "r-2",
        author: "Diana Isac",
        body: "Yes please! I'm a Fellow newcomer, would love to connect.",
        createdAt: now - 1000 * 60 * 60 * 36,
      },
    ],
  },
  {
    id: "n-5",
    kind: "need",
    author: "Camille Newsom",
    role: "AMI Fellow",
    body: "Want a follow-up loop on every Beg-Brag-What-If — what happened, what got built, who connected. A 'now what?' email or dashboard.",
    tags: ["bbwi", "follow-up"],
    color: "",
    rotation: -2.0,
    createdAt: now - 1000 * 60 * 60 * 50,
    replies: [],
  },
  {
    id: "n-6",
    kind: "offer",
    author: "Reece Gardner",
    role: "Fellow & Host",
    body: "Building the AMI member directory + Offers/Needs board as a proper app. Vibe-coding it this month — pilot in Raleigh.",
    tags: ["product", "directory"],
    color: "",
    rotation: 1.2,
    createdAt: now - 1000 * 60 * 60 * 6,
    replies: [
      {
        id: "r-3",
        author: "Spencer Karns",
        body: "I'll user-test it with the cohort. Ping me when there's a build.",
        createdAt: now - 1000 * 60 * 60 * 4,
      },
    ],
  },
  {
    id: "n-7",
    kind: "need",
    author: "Anna Wilson",
    role: "Newcomer · Duke",
    body: "Want a printable AMI leaflet with every attendee, role, photo, contact. The paper version is rare and valuable.",
    tags: ["directory", "print"],
    color: "",
    rotation: -2.8,
    createdAt: now - 1000 * 60 * 60 * 60,
    replies: [],
  },
  {
    id: "n-8",
    kind: "offer",
    author: "Yessica Herrera",
    role: "Artist-in-Residence",
    body: "Can design the AMI Playground daily-prompt experience — short rituals to keep the 'young soul' alive between gatherings.",
    tags: ["design", "playground"],
    color: "",
    rotation: 2.0,
    createdAt: now - 1000 * 60 * 60 * 8,
    replies: [],
  },
  {
    id: "n-9",
    kind: "need",
    author: "Christian Williams",
    role: "Speaker · J.P. Morgan",
    body: "Looking for AMI introductions to founders building responsibly with AI — happy to make warm bank intros in return.",
    tags: ["startups", "AI"],
    color: "",
    rotation: -1.5,
    createdAt: now - 1000 * 60 * 60 * 10,
    replies: [],
  },
  {
    id: "n-10",
    kind: "offer",
    author: "Nigel Jacob",
    role: "City of Boston · Speaker",
    body: "Will host an AMI delegation at City Hall for a tour of the New Urban Mechanics lab next time you're in Boston.",
    tags: ["smart cities", "Boston"],
    color: "",
    rotation: 1.6,
    createdAt: now - 1000 * 60 * 60 * 14,
    replies: [],
  },
];
